version: '3'
services:
  postgres:
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      DB_NAME: ng_bank_db
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgres

volumes:
  db-data: