version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      DB_NAME: ng_bank_db
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgres

  ng-api:
    container_name: ng-api
    build:
      context: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: 'postgresql://postgres:password@postgres:5432/ng_bank_db?schema=banking'
      JWT_SECRET: 'my-s&cr&t-K&Y'
    volumes:
      - ng-api:/usr/app
    depends_on:
      - postgres

volumes:
  db-data:
  ng-api: